Repository Tournamanager/api, pull requests merged in 2019-11, with the labels that each got.

#96 added cors policy
  src/main/java/com/fontys/api/configurations/WebConfig.java
Labels: enhancement

#98 Updated the tests so that mocking the repositories is no longer done …
  src/test/java/com/fontys/api/mockrepositories/MockTeamRepository.java
  src/test/java/com/fontys/api/mockrepositories/MockUserRepository2.java
  src/test/java/com/fontys/api/service/TeamServiceTest.java
  src/test/java/com/fontys/api/service/UserServiceTest.java
Labels: Improvement

#105 Fixes #103
  pom.xml
  src/main/java/com/fontys/api/configurations/WebConfig.java
  src/main/java/com/fontys/api/configurations/WebFluxConfig.java
Labels: bug

#112 Enhancement/update team
  src/main/java/com/fontys/api/mutations/TeamMutation.java
  src/main/java/com/fontys/api/service/TeamService.java
  src/test/java/com/fontys/api/service/TeamServiceTest.java
Labels: enhancement
